#服务注册中心的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.109.5:32605/eureka/,http://192.168.109.6:32605/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#服务的端口为8769
server:
  port: 8769
#服务名为service-zuul
spring:
  application:
    name: service-zuul
#以/api-a/ 开头的请求都转发给service-ribbon服务；以/api-b/开头的请求都转发给service-feign服务
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign
